# Generated by Django 3.0.5 on 2020-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ddl_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
