# Generated by Django 3.0.5 on 2020-05-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0004_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddl_killer.Course')),
            ],
        ),
    ]
