# Generated by Django 3.0.5 on 2020-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0007_auto_20200501_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ddl_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
