# Generated by Django 3.0.5 on 2020-05-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0009_auto_20200504_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddl_killer.Course')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddl_killer.Resource')),
            ],
        ),
    ]
