# Generated by Django 3.0.5 on 2020-05-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0011_auto_20200505_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='notification_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='notification_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
