# Generated by Django 3.0.5 on 2020-05-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0012_auto_20200507_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='is_admin',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='is_admin',
            new_name='isAdmin',
        ),
    ]
