# Generated by Django 3.0.5 on 2020-05-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0013_auto_20200507_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notification_alert',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notification_time',
        ),
    ]
