# Generated by Django 3.0.5 on 2020-05-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0016_auto_20200514_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
