# Generated by Django 3.0.5 on 2020-05-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0017_usertask_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddl_killer.Course')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddl_killer.Note')),
            ],
        ),
    ]
