# Generated by Django 3.0.5 on 2020-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0018_coursenote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ddl_alert',
            field=models.BooleanField(default=True),
        ),
    ]
