# Generated by Django 2.2 on 2020-05-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0022_user_ddl_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityKeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('pri_key', models.CharField(max_length=256)),
                ('pub_key', models.CharField(max_length=256)),
            ],
        ),
    ]
