# Generated by Django 3.0.5 on 2020-06-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0025_passwordmodificationrecord'),
        ('ddl_killer', '0025_report'),
    ]

    operations = [
    ]
