# Generated by Django 3.0.5 on 2020-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0027_task_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='repeat',
        ),
        migrations.AddField(
            model_name='usertask',
            name='repeat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
