# Generated by Django 3.0.5 on 2020-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_killer', '0028_auto_20200611_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='repeat',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
